"""Remove cyclic reference

Revision ID: f5ac2d88ffd2
Revises: a37dcaadf54b
Create Date: 2023-11-24 00:57:18.896521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ac2d88ffd2'
down_revision: Union[str, None] = 'a37dcaadf54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
